language: node_js
node_js:
  - "node"
os: osx
osx_image: xcode8
before_install:
  - brew update
  - brew install wine --without-x11
  - brew install mono
  - brew install gnu-tar graphicsmagick xz
script: node_modules/.bin/build -mwl
