language: node_js
node_js:
  - "node"
os: linux
dist: trusty
sudo: required
matrix:
  include:
    - os: osx
      osx_image: xcode8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install icnsutils graphicsmagick; fi
script: node_modules/.bin/build
deploy:
  provider: releases
  api_key:
    secure:
  file:

  skip_cleanup: true
  on:
    tags: true
