language: node_js
node_js:
  - "node"
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install icnsutils graphicsmagick; fi
script: node_modules/.bin/build
